name: Martin Escardo
markdown: kramdown
exclude:
  - "makefile"
  - "Gemfile"
  - "Gemfile.lock"
  - "*.agdai"
  - "*.lagda"
  - "*.agda"
  - "*.hs"
  - "*.hi"
  - "*.o"
  - "README.md"
  - "INSTALL.md"
  - "build"
  - "buildlocally"
  - "buildloop"
  - "fastloop"
  - "generatehtml"
  - "generatepdf"
  - "illiterate"
  - "illiterator"
  - "agdatomd"
  - "replace"
  - "slowloop"
  - "test"
  - "html/"
  - "agda/"
  - "vendor/"
